spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dc?serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: dcuser
    password: dcuser
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    # show-sql: true
    database: mysql

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

    default-property-inclusion: non_null
    mapper:
      sort-properties-alphabetically: true

  data:
    redis:
      repositories:
        enabled: true

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 0
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 8
      min-idle: 0


  session:
    timeout: 2000
    store-type: none
    redis:
      namespace: evidence

server:
  port: 8095

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.imengyu.datacenter.entity


